package net.osplay.data.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import net.osplay.data.bean.Account;
import net.osplay.data.bean.Community;

import net.osplay.data.db.AccountDao;
import net.osplay.data.db.CommunityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;
    private final DaoConfig communityDaoConfig;

    private final AccountDao accountDao;
    private final CommunityDao communityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        communityDaoConfig = daoConfigMap.get(CommunityDao.class).clone();
        communityDaoConfig.initIdentityScope(type);

        accountDao = new AccountDao(accountDaoConfig, this);
        communityDao = new CommunityDao(communityDaoConfig, this);

        registerDao(Account.class, accountDao);
        registerDao(Community.class, communityDao);
    }
    
    public void clear() {
        accountDaoConfig.clearIdentityScope();
        communityDaoConfig.clearIdentityScope();
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public CommunityDao getCommunityDao() {
        return communityDao;
    }

}
